=== Aroma-UI/CrossMobile/cmioslayer/src/main/resources/org/crossmobile/backend/desktop/skin/skin.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT chassis (image|screen|led|power|back|home|action|meta)*>
<!ATTLIST chassis
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    decorated CDATA #IMPLIED
    resize CDATA #IMPLIED
    info CDATA #IMPLIED
    idiom CDATA #IMPLIED
    descr CDATA #IMPLIED
  >

<!ELEMENT image EMPTY>
<!ATTLIST image
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    file CDATA #IMPLIED
  >

<!ELEMENT screen EMPTY>
<!ATTLIST screen
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    stretch CDATA #IMPLIED
  >

<!ELEMENT led EMPTY>
<!ATTLIST led
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    imageoff CDATA #IMPLIED
    imageon CDATA #IMPLIED
    orientation CDATA #IMPLIED
    autorotate CDATA #IMPLIED
  >

<!ELEMENT power EMPTY>
<!ATTLIST power
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    imagedown CDATA #IMPLIED
    imageup CDATA #IMPLIED
    orientation CDATA #IMPLIED
    autorotate CDATA #IMPLIED
  >

<!ELEMENT back EMPTY>
<!ATTLIST back
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    imagedown CDATA #IMPLIED
    imageup CDATA #IMPLIED
    orientation CDATA #IMPLIED
    autorotate CDATA #IMPLIED
  >

<!ELEMENT home EMPTY>
<!ATTLIST home
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    imagedown CDATA #IMPLIED
    imageup CDATA #IMPLIED
    orientation CDATA #IMPLIED
    autorotate CDATA #IMPLIED
  >

<!ELEMENT action EMPTY>
<!ATTLIST action
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
    imagedown CDATA #IMPLIED
    imageup CDATA #IMPLIED
    orientation CDATA #IMPLIED
    autorotate CDATA #IMPLIED
  >

<!ELEMENT meta EMPTY>
<!ATTLIST meta
    priority CDATA #IMPLIED
    info CDATA #IMPLIED
    descr CDATA #IMPLIED
  >

=== Aroma-UI/CrossMobile/cmutils/cmutils-common/src/main/resources/org/crossmobile/backend/desktop/skin/pad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE chassis SYSTEM "skin.dtd">-->
<chassis width="816" height="1126" idiom="pad" device="simulator">
    <meta priority="30" info="Pad Simulator" descr="An emulator-like big screen resolution (768x1024) skin"/>
    <image x="0" y="0" width="816" height="1126" file="pad/chassis.png"/>
    <screen x="24" y="40" width="768" height="1024"/>
    <led x="640" y="20" width="11" height="11" imageon="pad/ledgreen.png" imageoff="pad/ledred.png"/>
    <power x="390" y="0" width="46" height="46" imagedown="pad/power_down.png" imageup="pad/power_up.png"/>
    <back x="278" y="1068" width="42" height="42" imagedown="pad/back_down.png" imageup="pad/back_up.png"/>
    <home x="424" y="1068" width="42" height="42" imagedown="pad/home_down.png" imageup="pad/home_up.png"/>
    <action x="494" y="1068" width="42" height="42" imagedown="pad/action_down.png" imageup="pad/action_up.png"/>
</chassis>

=== Aroma-UI/CrossMobile/cmutils/cmutils-common/src/main/resources/org/crossmobile/backend/desktop/skin/phone-s.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE chassis SYSTEM "skin.dtd">-->
<chassis width="368" height="589" idiom="phone" device="simulator">
    <meta priority="70" info="Phone short Simulator" descr="An emulator-like short small screen resolution (320x480) skin"/>
    <image x="0" y="0" width="368" height="589" file="phone/chassis.png"/>
    <screen x="24" y="50" width="320" height="480"/>
    <led x="330" y="23" width="11" height="11" imageoff="phone/ledred.png" imageon="phone/ledgreen.png"/>
    <power x="20" y="16" width="23" height="23" imagedown="phone/power_down.png" imageup="phone/power_up.png"/>
    <back x="54" y="531" width="38" height="38" imagedown="phone/back_down.png" imageup="phone/back_up.png"/>
    <home x="201" y="531" width="38" height="38" imagedown="phone/home_down.png" imageup="phone/home_up.png"/>
    <action x="273" y="531" width="38" height="38" imagedown="phone/action_down.png" imageup="phone/action_up.png"/>
</chassis>
